# Timeout in seconds before auto-boot.
timeout: 3

# NexusOS boot entry.
/NexusOS
    # Use the Limine boot protocol.
    protocol: limine

    # Path to the kernel ELF. boot():/ is the partition containing limine.conf.
    path: boot():/boot/kernel
